### ISSUE TITLE
embed.author.icon_url: Scheme "undefined" is not supported. Scheme must be one of ('http', 'https').

### ISSUE THREAD

**Issue by LokeshSen002** [SCDerox/discord-inv#1]
const inviteurl = 'https://discord.gg/ee7ryDG';

discordInv.getInv(discordInv.getCodeFromUrl(inviteurl)).then(invite => {
    const embed = new Discord.MessageEmbed()
    .setAuthor(`Information About ${invite.guild.name}`,`${invite.iconURL}`)
    .setThumbnail(`${invite.iconURL}`)
    .setDescription(`Server Name: ${invite.guild.name}\nServer ID: ${invite.guild.id}\nServer Feature: ${invite.guild.features}`)
    message.channel.send(embed)
    console.log(invite)
}).catch(error => console.log(error))

**Comment by SCDerox** [comment]
So this is not actually an issue with this package. Sometimes guilds don't have an icon. In this case the package will return "undefined" in the `invite.iconURL` field. You should check if the key is set or not before passing the value to discord.js.

Feel free to comment on this issue if you need more help ^^
